namespace Syn.Core.SqlSchemaGenerator.Models;

/// <summary>
/// Represents the primary key constraint for a table.
/// </summary>
public class PrimaryKeyDefinition
{
    /// <summary>
    /// The name of the primary key constraint. Optional.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// The list of column names that form the primary key.
    /// </summary>
    public List<string> Columns { get; set; } = new();

    /// <summary>
    /// Indicates whether the primary key is clustered.
    /// </summary>
    public bool IsClustered { get; set; } = true;

    /// <summary>
    /// Optional flag to indicate if the key is auto-generated (e.g. via EF).
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// Optional metadata for future extensibility.
    /// </summary>
    public Dictionary<string, object> Metadata { get; set; } = new();
}