namespace Syn.Core.SqlSchemaGenerator.Models;

/// <summary>
/// Represents a unique constraint on one or more columns.
/// </summary>
public class UniqueConstraintDefinition
{
    /// <summary>
    /// The name of the unique constraint. Optional.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// The list of column names that must be unique together.
    /// </summary>
    public List<string> Columns { get; set; } = new();

    /// <summary>
    /// Optional flag to indicate if the constraint is auto-generated (e.g. via EF).
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;
    public string? Description { get; set; }

    /// <summary>
    /// Optional metadata for future extensibility.
    /// </summary>
    public Dictionary<string, object> Metadata { get; set; } = new();
}